---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ '{{ ansible_os_family }}' }}.yml"

- name: Define packages_to_install variable.
  set_fact:
    packages_to_install: "{{ '{{ __packages_to_install | list }}' }}"
  when: packages_to_install is not defined

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Do more things...



# Configure all the things.
- include: configure-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: configure-Debian.yml
  when: ansible_os_family == 'Debian'
